# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: testpb.proto

from collections.abc import AsyncGenerator, Iterable, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import (
    ConnectASGIApplication,
    ConnectWSGIApplication,
    Endpoint,
    EndpointSync,
)

from . import testpb_pb2 as testpb__pb2


class TestService(Protocol):
    async def unary_call_with_all_different_parameter_types(
        self, request: testpb__pb2.ExtendedTestMessage, ctx: RequestContext
    ) -> testpb__pb2.ExtendedTestMessage:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class TestServiceASGIApplication(ConnectASGIApplication[TestService]):
    def __init__(
        self,
        service: TestService | AsyncGenerator[TestService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/armeria.grpc.testing.TestService/UnaryCallWithAllDifferentParameterTypes": Endpoint.unary(
                    method=MethodInfo(
                        name="UnaryCallWithAllDifferentParameterTypes",
                        service_name="armeria.grpc.testing.TestService",
                        input=testpb__pb2.ExtendedTestMessage,
                        output=testpb__pb2.ExtendedTestMessage,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.unary_call_with_all_different_parameter_types,
                )
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/armeria.grpc.testing.TestService"


class TestServiceClient(ConnectClient):
    async def unary_call_with_all_different_parameter_types(
        self,
        request: testpb__pb2.ExtendedTestMessage,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> testpb__pb2.ExtendedTestMessage:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnaryCallWithAllDifferentParameterTypes",
                service_name="armeria.grpc.testing.TestService",
                input=testpb__pb2.ExtendedTestMessage,
                output=testpb__pb2.ExtendedTestMessage,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class TestServiceSync(Protocol):
    def unary_call_with_all_different_parameter_types(
        self, request: testpb__pb2.ExtendedTestMessage, ctx: RequestContext
    ) -> testpb__pb2.ExtendedTestMessage:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class TestServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: TestServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/armeria.grpc.testing.TestService/UnaryCallWithAllDifferentParameterTypes": EndpointSync.unary(
                    method=MethodInfo(
                        name="UnaryCallWithAllDifferentParameterTypes",
                        service_name="armeria.grpc.testing.TestService",
                        input=testpb__pb2.ExtendedTestMessage,
                        output=testpb__pb2.ExtendedTestMessage,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.unary_call_with_all_different_parameter_types,
                )
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/armeria.grpc.testing.TestService"


class TestServiceClientSync(ConnectClientSync):
    def unary_call_with_all_different_parameter_types(
        self,
        request: testpb__pb2.ExtendedTestMessage,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> testpb__pb2.ExtendedTestMessage:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnaryCallWithAllDifferentParameterTypes",
                service_name="armeria.grpc.testing.TestService",
                input=testpb__pb2.ExtendedTestMessage,
                output=testpb__pb2.ExtendedTestMessage,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
