# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greet.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'greet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"\x9b\x02\n\x08Greeting\x12\x1c\n\x08nickname\x18\x01 \x01(\tH\x00R\x08nickname\x12\x37\n\tfull_name\x18\x02 \x01(\x0b\x32\x18.greet.Greeting.FullNameH\x00R\x08\x66ullName\x12:\n\nknown_name\x18\x03 \x01(\x0e\x32\x19.greet.Greeting.KnownNameH\x00R\tknownName\x1a\x46\n\x08\x46ullName\x12\x1d\n\nfirst_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n\tlast_name\x18\x02 \x01(\tR\x08lastName\",\n\tKnownName\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x41LICE\x10\x01\x12\x07\n\x03\x42OB\x10\x02\x42\x06\n\x04name\">\n\x0fGreetingRequest\x12+\n\x08greeting\x18\x01 \x01(\x0b\x32\x0f.greet.GreetingR\x08greeting\"*\n\x10GreetingResponse\x12\x16\n\x06result\x18\x01 \x01(\tR\x06result2J\n\x0cGreetService\x12:\n\x05Greet\x12\x16.greet.GreetingRequest\x1a\x17.greet.GreetingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GREETING']._serialized_start=23
  _globals['_GREETING']._serialized_end=306
  _globals['_GREETING_FULLNAME']._serialized_start=182
  _globals['_GREETING_FULLNAME']._serialized_end=252
  _globals['_GREETING_KNOWNNAME']._serialized_start=254
  _globals['_GREETING_KNOWNNAME']._serialized_end=298
  _globals['_GREETINGREQUEST']._serialized_start=308
  _globals['_GREETINGREQUEST']._serialized_end=370
  _globals['_GREETINGRESPONSE']._serialized_start=372
  _globals['_GREETINGRESPONSE']._serialized_end=414
  _globals['_GREETSERVICE']._serialized_start=416
  _globals['_GREETSERVICE']._serialized_end=490
# @@protoc_insertion_point(module_scope)
