name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write

concurrency:
  # Cancel in-progress jobs for PRs only
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-15
          - ubuntu-24.04
          - windows-2025
        python:
          - "3.10"
          - "3.13"
        coverage:
          - "nocov"
        # Test oldest and newest on all OS's, but others only on one
        # to save CI load.
        include:
          - os: ubuntu-24.04
            python: "3.11"
            coverage: "nocov"
          - os: ubuntu-24.04
            python: "3.12"
            coverage: "nocov"
          # Enable coverage on just one job
          - os: ubuntu-24.04
            python: "3.13"
            coverage: "cov"
          - os: ubuntu-24.04
            python: "3.14.0-rc.2"
            coverage: "nocov"

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python }}

      - run: uv lock --check

      - name: run lints
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          uv run ruff format --check .
          uv run ruff check .
          uv run pyright

      - name: run tests
        run: uv run pytest ${{ matrix.coverage == 'cov' && '--cov=connecpy --cov-report=xml' || '' }}

      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        if: ${{ matrix.coverage == 'cov' }}

  publish:
    runs-on: ubuntu-24.04
    needs: build
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: pyproject.toml

      - run: uv build

      - uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
